Repository 42-Cursus-Ft-transcendence/Ft_transcendence, pull requests merged in 2025-07, with the labels that each got.

#11 Feature : 2FA, Modify : Prefix all backend routes with /api
  src/back/package-lock.json
  src/back/package.json
  src/back/src/db/db.ts
  src/back/src/routes/userRoutes.ts
  src/back/src/types/auth.d.ts
  src/front/public/js/controllers/loginController.js
  src/front/public/js/controllers/loginController.js.map
  src/front/public/js/controllers/menuController.js
  src/front/public/js/controllers/menuController.js.map
  src/front/public/js/controllers/signupController.js
  src/front/public/js/controllers/signupController.js.map
  src/front/src/controllers/loginController.ts
  src/front/src/controllers/menuController.ts
  src/front/src/controllers/signupController.ts
Labels: status : pending

#13 overhaul request/response logging
  src/back/.env.backend
  src/back/package-lock.json
  src/back/package.json
  src/back/src/plugins/logger.ts
  src/back/src/routes/userRoutes.ts
  src/back/src/server.ts
Labels: status : request review

#23 Hotfix : server.ts(Parenthesis closing issues)
  src/back/src/server.ts
Labels: status : hotfix

#29 bugfix: disconnections and zoom on page refresh
  src/front/public/js/controllers/pongController.js
  src/front/public/js/controllers/pongController.js.map
  src/front/public/js/index.js
  src/front/public/js/index.js.map
  src/front/src/controllers/pongController.ts
  src/front/src/index.ts
Labels: status : bug
